version: 2.1
default_build_environment: &default_build_environment
  docker:
    - image: cimg/base:stable
      auth:
        username: codainternaltools
        password: $DOCKERHUB_PASSWORD
python_build: &python_build
    docker:
      - image: cimg/python:3.10.0
        auth:
          username: codainternaltools
          password: $DOCKERHUB_PASSWORD
orbs:
  utils: coda/utils@<<pipeline.parameters.dev-orb-version>>
  circleci-cli: circleci/circleci-cli@0.1.9
  orb-tools: circleci/orb-tools@10.1.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  slack: circleci/slack@4.5.0

# Pipeline Parameters
## These parameters are used internally by orb-tools.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

commands:


jobs:
  integration-test-notify:
    <<: *default_build_environment
    steps:
      - checkout
      - utils/notify

  integration-test-slack:
    <<: *default_build_environment
    steps:
      - checkout
      - utils/slack-notify-waiting-for-approval:
          slack_bot_token: ${SLACK_BOT_TOKEN}

  pack-files:
    <<: *python_build
    parameters:
      publish-token-variable:
        type: env_var_name
        default: ORB_PUBLISHING_TOKEN
        description: publishing token
    steps:
      - checkout
      - run: 
          command: make wrap-python-files
          name: Add shell script around python files
      - circleci-cli/install
      - orb-tools/pack
      - orb-tools/publish:
          orb-ref: coda/utils@dev:alpha
          token-variable: <<parameters.publish-token-variable>>

  publish-major:
    <<: *python_build
    parameters:
      publish-token-variable:
        type: env_var_name
        default: ORB_PUBLISHING_TOKEN
        description: publishing token
    steps:
      - checkout
      - run: 
          command: make wrap-python-files
          name: Add shell script around python files
      - circleci-cli/install
      - orb-tools/pack
      - orb-tools/publish:
          orb-ref: coda/utils@dev:ci_publish
          token-variable: <<parameters.publish-token-variable>>
      - orb-tools/increment:
          token-variable: <<parameters.publish-token-variable>>
          segment: major 
          orb-ref: coda/utils@dev:ci_publish

  publish-minor:
    <<: *python_build
    parameters:
      publish-token-variable:
        type: env_var_name
        default: ORB_PUBLISHING_TOKEN
        description: publishing token
    steps:
      - checkout
      - run: 
          command: make wrap-python-files
          name: Add shell script around python files
      - circleci-cli/install
      - orb-tools/pack
      - orb-tools/publish:
          orb-ref: coda/utils@dev:ci_publish
          token-variable: <<parameters.publish-token-variable>>
      - orb-tools/increment:
          token-variable: <<parameters.publish-token-variable>>
          segment: minor 
          orb-ref: coda/utils@dev:ci_publish

workflows:
  publish-dev:
    jobs:
      - pack-files:
          context:
            - dockerhub
            - orb-publishing
          filters:
            branches:
              ignore: main
          publish-token-variable: ORB_PUBLISHING_TOKEN
  publish-prod:
    jobs:
      - minor-semver:
          type: approval
          filters:
            branches:
              only:
                - main
      - major-semver:
          type: approval
          filters:
            branches:
              only:
                - main
      - publish-major:
          context:
            - dockerhub
            - orb-publishing
            - util
          publish-token-variable: ORB_PUBLISHING_TOKEN
          requires:
            - major-semver
          filters:
            branches:
              only:
                - main
      - publish-minor:
          context:
            - dockerhub
            - orb-publishing
            - util
          publish-token-variable: ORB_PUBLISHING_TOKEN
          requires:
            - minor-semver
          filters:
            branches:
              only:
                - main