version: 2.1
default_build_environment: &default_build_environment
  docker:
    - image: cimg/base:stable
      auth:
        username: codainternaltools
        password: $DOCKERHUB_PASSWORD


orbs:
  utils: coda/utils@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0.3
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  circleci-user:
    description: The user who published orb changes
    type: string
    default: ''

commands:
  bootstrap_pipeline_circleci_user:
    steps:
      - run:
          name: Initialize CIRCLE_USERNAME from pipeline
          command: |
            echo "export CIRCLE_USERNAME=<< pipeline.parameters.circleci-user >>" >> $BASH_ENV
            source $BASH_ENV

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/review
      - shellcheck/check:
          exclude: 'SC2148,SC2038,SC2086,SC2002,SC2016'
      - orb-tools/publish:
          context: 
            - dockerhub
            - orb-publishing
          orb-name: coda/utils
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
          vcs-type: github
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          requires:
            - orb-tools/publish
          vcs-type: github
          filters:
              branches:
                  ignore: main
  publish:
    jobs:
      - orb-tools/publish:
          context: 
            - dockerhub
            - orb-publishing
            - util
          filters:
            branches:
              only:
                - main
          orb-name: coda/utils
          pub-type: production
          requires:
            - integration-test-notify
            - integration-test-slack
            - utils/cancel-older-awaiting-approvals
          vcs-type: github
          circleci-token: ORB-PUBLISHING-TOKEN