version: '2.1'
orbs:
  utils: coda/utils@dev:<<pipeline.git.revision>>'
  orb-tools: circleci/orb-tools@11.1
  bats: circleci/bats@1.0


jobs:
  integration-test-notify:
    <<: *default_build_environment
    steps:
      - checkout
      - utils/notify:
          on_success: true

  integration-test-slack:
    <<: *default_build_environment
    steps:
      - checkout
      - bootstrap_pipeline_circleci_user
      - utils/slack-notify-waiting-for-approval:
          slack_bot_token: ${SLACK_ACCESS_TOKEN}

  integration-test-cancel-older-jobs:
    <<: *default_build_environment
    steps:
      - checkout
      - utils/cancel-older-awaiting-approvals

workflows:
  test-deploy:
    jobs:
      - integration-test-notify:
          context:
            - dockerhub
            - orb-publishing
            - util
            - ops-genie
      - integration-test-slack:
          context:
            - dockerhub
            - orb-publishing
            - util
            - slack
      - utils/cancel-older-awaiting-approvals:
          context:
            - dockerhub
            - orb-publishing
            - util

